In [37]:
import numpy as np
import matplotlib.pyplot as plt

In [38]:
np.random.standard_normal(10)

array([ 0.16075034, -0.43373882, -0.66359637, -0.17391065,  1.13600631,
        2.20253295,  0.27521777, -1.07224763, -0.3982236 ,  0.03273627])

In [39]:
#一个4*4递推矩阵
recurrence_matrix = np.array([[0, 0.5, 0.25, 0.25], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0]])
print(recurrence_matrix)
# 初始向量
initial_vector = np.array([1, 2, 3, 4])
# 计算前10个元素
for i in range(10):
    print(np.dot(recurrence_matrix, initial_vector))
    initial_vector = np.dot(recurrence_matrix, initial_vector)
# 计算最终稳定数字
final_vector = np.dot(recurrence_matrix, initial_vector)

[[0.   0.5  0.25 0.25]
 [1.   0.   0.   0.  ]
 [0.   1.   0.   0.  ]
 [0.   0.   1.   0.  ]]
[2.75 1.   2.   3.  ]
[1.75 2.75 1.   2.  ]
[2.125 1.75  2.75  1.   ]
[1.8125 2.125  1.75   2.75  ]
[2.1875 1.8125 2.125  1.75  ]
[1.875  2.1875 1.8125 2.125 ]
[2.078125 1.875    2.1875   1.8125  ]
[1.9375   2.078125 1.875    2.1875  ]
[2.0546875 1.9375    2.078125  1.875    ]
[1.95703125 2.0546875  1.9375     2.078125  ]


In [40]:
# 计算稳定状态
def calculate_stable_state(transition_matrix,initial_state,tolerance=1e-6,max_iterations=1000):
    stable_state = initial_state   
    for _ in range(max_iterations):
        new_state = np.dot(transition_matrix, stable_state)
        # 检查收敛条件
        if np.linalg.norm(new_state - stable_state) < tolerance:
            break
        stable_state = new_state
        if _ == max_iterations - 1:
           print("未满足收敛条件，已达到迭代数量上限")
    return stable_state

In [41]:
calculate_stable_state(recurrence_matrix,initial_vector,tolerance=1e-15)

array([2., 2., 2., 2.])